### PR TITLE
Use app extension safe APIs

### PR DESCRIPTION
**Pull request by nderkach**
Thanks for building this!

This PR makes the framework app extension safe so that it can be integrated into apps with extensions.

### CODE REVIEW

**Comment by JoeMatt** [comment]
A more elegant solution may be a simple wrapper func

```swift

internal func RootViewController() -> UIViewController? {
    #if BUILD_FOR_EXTENSION
    return nil
    #else
    return UIApplication.shared.keyWindow?.rootViewController
    #endif
}
```

And then in the podsubspec you add

```ruby
  s.subspec 'AppExtension' do |sp|
	sp.pod_target_xcconfig = {
    'APPLICATION_EXTENSION_API_ONLY' => true,
    'BUILD_FOR_EXTENSION' => '-D\'BUILD_FOR_EXTENSION\'',
    'OTHER_SWIFT_FLAGS' => '$(WIDGET_SUBSPEC_INCLUDED) $(BUILD_FOR_EXTENSION)'
  }
  end
```

Anyone wanting to build an extension would therefore add

```ruby
target MyExtension
	pod 'Hero/AppExtension`
end
```

Another method is to put two versions of the function in different source files and only add the correct ones to each target though that's probably a little more conflated.

3rd, you could do the same thing, remove the subspec, and just do it all with 
NSStringClassFromString.

I was trying to find an
#if //some stock XCode define for extensions only

but couldn't find one, there must be though no?  like target(extension)

**Comment by JoeMatt** [comment]
A post on the subject,
https://miqu.me/blog/2016/11/28/app-extensions-xcode-and-cocoapods-omg/

**Comment by james-ff** [comment]
+1 Would like to be able to use this library in a share extension

**Comment by JoeMatt** [comment]
merged in previous PRs.

**Pull request closed without merging**
