### PR TITLE
Use custom snapshot for views that implements HeroCustomSnapshotView

### PR DESCRIPTION
**Pull request by ManueGE**
I found very useful the **Optimized** snapshots for `UIImageView`, `UIStackView`, `Bars`, ... 

But at some point, I found myself needing my custom views a customized snapshot. To solve this issue, I created the `HeroCustomSnapshotView` protocol, that a view can implement in order to provide their own **optimized** snapshot. It has no impact in the rest of the library, but it can make it a little more flexible. 

If you like the idea but you'd like to use a better wording or a different approach, let me know, I'll be happy to help.

### CODE REVIEW

**Comment by ManueGE** [comment]
@SD10 do you think this PR makes sense? if you have any improvement I'll be happy to change or adapt my PR.

**Comment by ManueGE** [comment]
Added the changes to Changelog.

**Comment by ManueGE** [comment]
Hi @sd10 

Thanks for taking the time of merging master into it.

Do you need me to add any additional change to this PR?

**Comment by SD10** [comment]
@ManueGE This is good to go. I just didn't have the time to give it the final review last night 😅

**Comment by ManueGE** [comment]
Thank you very much @sd10, didn’t want to put more pressure on you, just asked in case you missed it. 

Thanks again. 😊

**Comment by SD10** [comment]
@ManueGE Happy New Year 🎉 Do you have any interest in helping me maintain Hero? 😄 You can reach out to me on Twitter at [_SD10_](https://twitter.com/_SD10_) if you want to talk more

**Pull request merged**
